/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NonEssentialsRouteImport } from './routes/non-essentials'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as IncomesRouteImport } from './routes/incomes'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EssentialsRouteImport } from './routes/essentials'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetCategoriesIdRouteImport } from './routes/budget-categories.$id'

const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NonEssentialsRoute = NonEssentialsRouteImport.update({
  id: '/non-essentials',
  path: '/non-essentials',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomesRoute = IncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialsRoute = EssentialsRouteImport.update({
  id: '/essentials',
  path: '/essentials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetCategoriesIdRoute = BudgetCategoriesIdRouteImport.update({
  id: '/budget-categories/$id',
  path: '/budget-categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/essentials': typeof EssentialsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/investments': typeof InvestmentsRoute
  '/non-essentials': typeof NonEssentialsRoute
  '/payments': typeof PaymentsRoute
  '/budget-categories/$id': typeof BudgetCategoriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/essentials': typeof EssentialsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/investments': typeof InvestmentsRoute
  '/non-essentials': typeof NonEssentialsRoute
  '/payments': typeof PaymentsRoute
  '/budget-categories/$id': typeof BudgetCategoriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/essentials': typeof EssentialsRoute
  '/expenses': typeof ExpensesRoute
  '/incomes': typeof IncomesRoute
  '/investments': typeof InvestmentsRoute
  '/non-essentials': typeof NonEssentialsRoute
  '/payments': typeof PaymentsRoute
  '/budget-categories/$id': typeof BudgetCategoriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/essentials'
    | '/expenses'
    | '/incomes'
    | '/investments'
    | '/non-essentials'
    | '/payments'
    | '/budget-categories/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/essentials'
    | '/expenses'
    | '/incomes'
    | '/investments'
    | '/non-essentials'
    | '/payments'
    | '/budget-categories/$id'
  id:
    | '__root__'
    | '/'
    | '/essentials'
    | '/expenses'
    | '/incomes'
    | '/investments'
    | '/non-essentials'
    | '/payments'
    | '/budget-categories/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EssentialsRoute: typeof EssentialsRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomesRoute: typeof IncomesRoute
  InvestmentsRoute: typeof InvestmentsRoute
  NonEssentialsRoute: typeof NonEssentialsRoute
  PaymentsRoute: typeof PaymentsRoute
  BudgetCategoriesIdRoute: typeof BudgetCategoriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-essentials': {
      id: '/non-essentials'
      path: '/non-essentials'
      fullPath: '/non-essentials'
      preLoaderRoute: typeof NonEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incomes': {
      id: '/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof IncomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essentials': {
      id: '/essentials'
      path: '/essentials'
      fullPath: '/essentials'
      preLoaderRoute: typeof EssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-categories/$id': {
      id: '/budget-categories/$id'
      path: '/budget-categories/$id'
      fullPath: '/budget-categories/$id'
      preLoaderRoute: typeof BudgetCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EssentialsRoute: EssentialsRoute,
  ExpensesRoute: ExpensesRoute,
  IncomesRoute: IncomesRoute,
  InvestmentsRoute: InvestmentsRoute,
  NonEssentialsRoute: NonEssentialsRoute,
  PaymentsRoute: PaymentsRoute,
  BudgetCategoriesIdRoute: BudgetCategoriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
